import type { NextPage } from 'next'
import Head from 'next/head'
import Menu from 'components/Menu'

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pagina de contato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu />
        contact
      </main>
    </div>
  )
}

export default Contact
