import Head from 'next/head'
import Menu from 'components/Menu'
import Posts from 'components/Posts'
import Container from 'components/Container'
import Footer from 'components/Footer'

const postsblog = [
  {
    title: 'Tudo o que você precisa saber sobre React JS',
    category: 'React JS',
    detailtitle: '2023',
    image: 'Link de imagem',
    content: 'Conteúdo'
  },
  {
    title: 'PHP vai morrer?',
    category: 'PHP',
    detailtitle: '<?php echo "Não vou morrer"; ?>',
    image: 'Link de imagem',
    content: 'Conteúdo'
  },
  {
    title: 'PHP vai morrer?',
    category: 'Dúvidas',
    detailtitle: '<?php echo "Não vou morrer"; ?>',
    image: 'Link de imagem',
    content: 'Conteúdo'
  },
  {
    title: 'Laravel tem muito a oferecer',
    category: 'Dúvidas',
    detailtitle: '',
    image: 'Link de imagem',
    content: 'Conteúdo'
  },
  {
    title: 'Vue, watchers e computers. Você precisa conhecer',
    category: 'Dúvidas',
    detailtitle: '',
    image: 'Link de imagem',
    content: 'Conteúdo'
  }
]

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Blog Auto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Container>
        <Posts posts={postsblog} />
      </Container>
      <Footer />
    </div>
  )
}

export default Home
